### ISSUE TITLE
Set PSMoveService Server address in PSMoveFreepieBridge

### ISSUE THREAD

**Issue by Peng180** [HipsterSloth/PSMoveFreepieBridge#1]
I'd like to change default server_address in PSMoveFreepieBridge, is there any setting file I could manually set server ip address?
I searched in the source code downloaded from release 16, I found "localhost" in both /PSMoveFreepieBridge/FreepieMoveClient.cpp and /thirdparty/headers/PSMoveService/SharedConstants.h . I changed the value to my server ip address(192.168.1.5), then opened PSMoveFreepieBridge.sln in VS2015 and build the project. The building was successful, after running PSMoveFreepieBridge.exe I got error messages as below.

> Unhandled Exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at FreepieWriter.FreepieWriter.freepie_io_6dof_write(Int32 index, Int32 length, FreepieData[] data)
   at FreepieWriter.FreepieWriter.WriteData(FreepieData data, Int32 freepieIndex) in C:\Users\Peng\Documents\GitHub\PSMoveFreepieBridge\FreepieWriter\FreepieWriter.cs:line 50
   at FreepieWriterBridge.FreepieWriterBridge.WriteToFreepie(freepie_io_6dof_data data, Int32 freepieIndex) in c:\users\peng\documents\github\psmovefreepiebridge\freepiewriterbridge\freepiewriterbridge.h:line 20
   at WriteToFreepie(freepie_io_6dof_data data, Int32 freepieIndex) in c:\users\peng\documents\github\psmovefreepiebridge\freepiewriterbridge\freepiewriterbridge.h:line 28

Any help would be appreciated. @HipsterSloth

**Comment by Peng180** [comment]
Screenshot
![capture](https://user-images.githubusercontent.com/35923649/47217611-835cdd80-d3db-11e8-8421-c9dc75af5c46.PNG)

**Comment by Peng180** [comment]
I could really use some help here guys.

**Comment by HipsterSloth** [comment]
I can't repro the issue you are getting but near as I can tell your local build is trying to load the 32-bit version of the freepie_io,dll instead of the 64-bit one? It looks like you are building the Release|x64 configuration. Have you tried the Release|AnyCPU configuration?

Separate from that, it does seem like having the ability to override the ip address is useful. I have a change that supports that in another branch that I just checked in:
https://github.com/HipsterSloth/PSMoveFreeieBridge/commit/6ecc146bf3d7e91d9f5cfe9915cec7188bc23d25

This is a custom build with that change:
[PSMoveFreepieBridge-Release17.zip](https://github.com/HipsterSloth/PSMoveFreepieBridge/files/2518275/PSMoveFreepieBridge-Release17.zip)

If that works for you I can fold this into the official release.

**Comment by Peng180** [comment]
Good job. 
I have tested the HMD tracking in the new release, it works perfectly. 
Thank you for your time and effort.

**Comment by T6BERRY** [comment]
I have a VirtualHMD LED ball and it works great in every respect except one.  In Steamvr the tracking is reversed for forward, back and sideways movements.  The height is correct though.  I've tried many suggestions but so far nothing has worked.  It's really frustrating because I'm so close.  Also, when I bend forward, my body position moves back and my controllers go away from me.  It's a really weird sensation.

**Comment by MacaberKahn** [comment]
Is there a way to change port though? I have trouble connecting to 9512, so I've been using 9514 for PSmoveService but I have no idea how to change it in FreepieBridge.

**Comment by AkayabeKimitsu** [comment]
@MacaberKahn
Source code is your friend.
